version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3
  aws-ecr: circleci/aws-ecr@7.2.0

jobs:
  deploy_on_lambda:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - aws-cli/setup:
          aws-region: AWS_REGION
      - run:
          name: "aws lambda update-function-code"
          command: |
            aws lambda update-function-code --region $AWS_REGION \
              --function-name cci-hello-serverless \
              --image-uri $AWS_ECR_ACCOUNT_URL/cci_hello_serverless:latest
  build_and_push_image_on_docker:
    docker:
      - image: cibuilds/docker:latest
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_ACCESSTOKEN
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build a Docker image"
          command: |
            cd azure
            docker build -t mfunaki/cci-hello-serverless-azure .
      - run:
          name: "Push to DockerHub"
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push mfunaki/cci-hello-serverless-azure

workflows:
  build_push_and_deploy_on_aws:
    jobs:
      - aws-ecr/build-and-push-image:
          context: aws
          create-repo: true
          path: ./aws
          repo: cci_hello_serverless
      - deploy_on_lambda:
          context:
            - aws
            - docker
          requires:
            - aws-ecr/build-and-push-image
  build_push_and_deploy_on_azure:
    jobs:
      - build_and_push_image_on_docker:
          context: docker
