version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.2.0

workflows:
  build_and_push_image_on_aws:
    jobs:
      - aws-ecr/build-and-push-image:
          context: aws, docker
          create-repo: true
          path: ./aws
          repo: cci_hello_serverless
      - run:
          command: |
            aws lambda update-function-code --region $AWS_REGION --function-name cci-hello-serverless ¥
              --image-url $AWS_ECR_ACCOUNT_URL/cci_hello_serverless:latest

